import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { users, profiles } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { sha256 } from "@/lib/auth";
import { rateLimitByIp } from "@/lib/rate-limit";
import { z } from "zod/v4";

const RESERVED_SUBDOMAINS = new Set([
  "api",
  "www",
  "admin",
  "auth",
  "me",
  "club",
  "app",
  "dashboard",
  "login",
  "signup",
  "settings",
  "profile",
  "search",
  "help",
  "about",
  "blog",
  "docs",
  "status",
  "support",
  "billing",
  "static",
  "assets",
  "public",
  "u",
  "taste-board",
  "gavin",
]);

const VALID_THEMES = [
  "default",
  "yc-orange",
  "terminal-green",
  "minimal-light",
  "cyberpunk",
] as const;

const publishSchema = z.object({
  // device_id: stable local machine identifier (generated by agent, stored in ~/.builderbio/config.json)
  device_id: z.string().min(8).max(128),
  // publish_token: returned on first publish, required for updates
  publish_token: z.string().optional(),
  // data_hash: SHA-256 of key stats for Unfiltered badge verification
  data_hash: z.string().length(64).optional(),
  // style_theme: visual theme for the profile page
  style_theme: z.enum(VALID_THEMES).default("default"),
  profile: z.object({
    summary: z.string().optional(),
    display_name: z.string().optional(),
    portrait: z.record(z.string(), z.unknown()).optional(),
    framework_sentences: z.array(z.string()).optional(),
    activity_map: z.record(z.string(), z.unknown()).optional(),
    behavioral_fingerprint: z.record(z.string(), z.unknown()).optional(),
    search_profile: z.record(z.string(), z.unknown()).optional(),
    sessions_analyzed: z.number().min(0).default(0),
    total_tokens: z.number().min(0).default(0),
  }),
  // Full BuilderBio data model (D + E) for rendering the rich profile page
  builderbio: z
    .object({
      D: z.record(z.string(), z.unknown()),
      E: z.record(z.string(), z.unknown()),
    })
    .optional(),
});

function buildSearchVector(
  profile: z.infer<typeof publishSchema>["profile"]
): string {
  const parts: string[] = [];
  if (profile.summary) parts.push(profile.summary);
  if (profile.framework_sentences)
    parts.push(profile.framework_sentences.join(" "));
  if (profile.search_profile) {
    const sp = profile.search_profile as Record<string, string[]>;
    if (sp.skills) parts.push(sp.skills.join(" "));
    if (sp.languages) parts.push(sp.languages.join(" "));
    if (sp.frameworks) parts.push(sp.frameworks.join(" "));
    if (sp.domains) parts.push(sp.domains.join(" "));
  }
  return parts.join(" ");
}

function generateToken(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Generate a unique short code for the subdomain.
 * 8 chars, lowercase alphanumeric — 36^8 = ~2.8 trillion combinations.
 */
function generateShortCode(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => chars[b % chars.length])
    .join("");
}

export async function POST(req: NextRequest) {
  // Rate limit: 5 req/min per IP
  const ip =
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null;
  const limited = rateLimitByIp(ip, "publish", 5);
  if (limited) return limited;

  try {
    const body = await req.json();

    // Normalize common payload variations before validation
    // Accept "theme" as alias for "style_theme"
    if (body.theme && !body.style_theme) {
      body.style_theme = body.theme;
    }
    // Accept various builderbio payload formats
    if (!body.builderbio) {
      // Case 1: { D: {...}, E: {...} } at top level
      if (body.D && body.E) {
        body.builderbio = { D: body.D, E: body.E };
      }
      // Case 2: { profile: {...}, extra: {...} } — extra is E, profile contains D-like data
      else if (body.extra && typeof body.extra === "object") {
        const D = body.D || body.profile?.D;
        if (D) {
          body.builderbio = { D, E: body.extra };
          if (body.profile?.D) delete body.profile.D;
        }
      }
      // Case 3: { profile: {..., D: {...}, E: {...} } } — D/E nested inside profile
      else if (body.profile?.D && body.profile?.E) {
        body.builderbio = { D: body.profile.D, E: body.profile.E };
        delete body.profile.D;
        delete body.profile.E;
      }
    }

    const parsed = publishSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid payload", details: parsed.error.issues },
        { status: 400 }
      );
    }

    const { device_id, publish_token, data_hash, style_theme, profile, builderbio } = parsed.data;

    if (!builderbio) {
      return NextResponse.json(
        {
          error: "Missing builderbio data",
          details:
            "The publish payload must include builderbio: { D: {...}, E: {...} }. Metadata-only publishes cannot render a BuilderBio page.",
        },
        { status: 400 }
      );
    }

    // Sync profile metadata from builderbio.D if available
    // D.profile is the authoritative source for stats
    if (builderbio?.D) {
      const dProfile = (builderbio.D as Record<string, unknown>).profile as Record<string, unknown> | undefined;
      if (dProfile) {
        if (typeof dProfile.total_sessions === "number" && dProfile.total_sessions > 0) {
          profile.sessions_analyzed = dProfile.total_sessions;
        }
        if (typeof dProfile.total_tokens === "number" && dProfile.total_tokens > 0) {
          profile.total_tokens = dProfile.total_tokens;
        }
        if (typeof dProfile.display_name === "string" && dProfile.display_name) {
          profile.display_name = dProfile.display_name;
        }
        if (typeof dProfile.summary === "string" && dProfile.summary) {
          profile.summary = dProfile.summary;
        }
      }
    }

    const searchVector = buildSearchVector(profile);
    const deviceIdHash = await sha256(device_id);
    const baseDomain =
      process.env.NEXT_PUBLIC_BASE_DOMAIN || "builderbio.dev";

    // --- Lookup existing user ---
    // Priority 1: publish_token (strongest auth — proves ownership)
    // Priority 2: device_id_hash (same device, same short code)

    let existingUser = null;

    if (publish_token) {
      const tokenHash = await sha256(publish_token);
      const rows = await db
        .select()
        .from(users)
        .where(eq(users.publishTokenHash, tokenHash))
        .limit(1);
      if (rows.length > 0) existingUser = rows[0];
    }

    if (!existingUser) {
      const rows = await db
        .select()
        .from(users)
        .where(eq(users.deviceIdHash, deviceIdHash))
        .limit(1);
      if (rows.length > 0) existingUser = rows[0];
    }

    // --- Update existing user ---
    if (existingUser) {
      await db
        .update(profiles)
        .set({
          summary: profile.summary,
          portrait: profile.portrait,
          frameworkSentences: profile.framework_sentences,
          activityMap: profile.activity_map,
          behavioralFingerprint: profile.behavioral_fingerprint,
          searchProfile: profile.search_profile,
          searchVector,
          builderBioData: builderbio,
          dataHash: data_hash || null,
          styleTheme: style_theme,
          sessionsAnalyzed: profile.sessions_analyzed,
          totalTokens: profile.total_tokens,
          updatedAt: new Date(),
        })
        .where(eq(profiles.userId, existingUser.id));

      // Update display name if provided
      if (profile.display_name) {
        await db
          .update(users)
          .set({ displayName: profile.display_name })
          .where(eq(users.id, existingUser.id));
      }

      // Backfill deviceIdHash if missing (for users created before this column existed)
      if (!existingUser.deviceIdHash) {
        await db
          .update(users)
          .set({ deviceIdHash })
          .where(eq(users.id, existingUser.id));
      }

      // Re-issue publish_token if user didn't have one saved locally
      let tokenToReturn: string | undefined;
      if (!publish_token) {
        const newToken = generateToken();
        const newTokenHash = await sha256(newToken);
        await db
          .update(users)
          .set({ publishTokenHash: newTokenHash })
          .where(eq(users.id, existingUser.id));
        tokenToReturn = newToken;
      }

      return NextResponse.json({
        success: true,
        url: `https://${existingUser.username}.${baseDomain}`,
        slug: existingUser.username,
        ...(tokenToReturn ? { publish_token: tokenToReturn } : {}),
      });
    }

    // --- Create new user with generated short code ---
    let shortCode = generateShortCode();

    // Ensure uniqueness (collision is extremely unlikely with 36^8 but check anyway)
    for (let attempt = 0; attempt < 5; attempt++) {
      if (RESERVED_SUBDOMAINS.has(shortCode)) {
        shortCode = generateShortCode();
        continue;
      }
      const collision = await db
        .select({ id: users.id })
        .from(users)
        .where(eq(users.username, shortCode))
        .limit(1);
      if (collision.length === 0) break;
      shortCode = generateShortCode();
    }

    const publishTokenNew = generateToken();
    const publishTokenHash = await sha256(publishTokenNew);

    const [newUser] = await db
      .insert(users)
      .values({
        username: shortCode,
        displayName: profile.display_name || null,
        publishTokenHash,
        deviceIdHash,
      })
      .returning({ id: users.id });

    await db.insert(profiles).values({
      userId: newUser.id,
      status: "published",
      isPublic: 1,
      summary: profile.summary,
      portrait: profile.portrait,
      frameworkSentences: profile.framework_sentences,
      activityMap: profile.activity_map,
      behavioralFingerprint: profile.behavioral_fingerprint,
      searchProfile: profile.search_profile,
      searchVector,
      builderBioData: builderbio,
      dataHash: data_hash || null,
      styleTheme: style_theme,
      sessionsAnalyzed: profile.sessions_analyzed,
      totalTokens: profile.total_tokens,
    });

    return NextResponse.json({
      success: true,
      url: `https://${shortCode}.${baseDomain}`,
      slug: shortCode,
      publish_token: publishTokenNew,
    });
  } catch (error) {
    console.error("Publish error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
