#!/usr/bin/env python3
"""
Assemble the upload payload for coding-dna profile sync.
Merges local stats with AI-generated analysis into a single JSON.
"""

import json
import sys
import os
from datetime import datetime

def main():
    stats_file = sys.argv[1] if len(sys.argv) > 1 else '/tmp/coding-dna-stats.json'
    analysis_file = sys.argv[2] if len(sys.argv) > 2 else '/tmp/coding-dna-analysis.json'
    output_file = sys.argv[3] if len(sys.argv) > 3 else '/tmp/coding-dna-payload.json'

    # Load local stats
    with open(stats_file, 'r') as f:
        stats = json.load(f)

    # Load AI analysis (generated by the AI tool using analysis-prompt.md)
    analysis = {}
    if os.path.exists(analysis_file):
        with open(analysis_file, 'r') as f:
            analysis = json.load(f)

    # Read version
    config_dir = os.path.expanduser('~/.coding-dna')
    version = '0.1.0'
    version_file = os.path.join(config_dir, 'skills', 'VERSION')
    if os.path.exists(version_file):
        with open(version_file, 'r') as f:
            version = f.read().strip()

    # Assemble payload
    payload = {
        'client_version': version,
        'sessions_analyzed': stats.get('sessions_analyzed', 0),
        'total_tokens': stats.get('total_tokens', 0),
        'summary': analysis.get('summary', ''),
        'portrait': analysis.get('portrait', {}),
        'framework_sentences': analysis.get('framework_sentences', []),
        'activity_map': stats.get('activity_map', {}),
        'behavioral_fingerprint': stats.get('behavioral_fingerprint', {}),
        'search_profile': {
            'skills': analysis.get('skills', []),
            'languages': analysis.get('languages', []),
            'frameworks': analysis.get('frameworks', []),
            'domains': analysis.get('domains', []),
        },
        'assembled_at': datetime.now().isoformat(),
    }

    with open(output_file, 'w') as f:
        json.dump(payload, f, indent=2)

    print(f'→ Payload assembled: {output_file}')
    print(f'  Sessions: {payload["sessions_analyzed"]}')
    print(f'  Tokens: ~{payload["total_tokens"]:,}')
    print(f'  Framework sentences: {len(payload["framework_sentences"])}')

if __name__ == '__main__':
    main()
